### PR TITLE
few more edits to sealed room section

### PR DESCRIPTION
**Pull request by gforney**

### CODE REVIEW

**Comment by rpeacoc** [comment]
Here's the new plots.  I'll commit the updated analytical values shortly

**Comment by gforney** [comment]
did you intend to attach some plots, I don't see anything

**Comment by rpeacoc** [comment]
They are attached to the email in my sent folder.  There should have been two PDF files.  You can just generate them with the bot … they look fine.

RP

**Comment by rpeacoc** [comment]
Do you have the email that Randy sent around a couple months back with thoughts on how we should reorganize the CFAST repository to better match the FDS one?  I actually want to do some of it and can’t find the email … I’d hate for him to realize I’ve ignored it this long.

RP

**Pull request merged**
