### PR TITLE
V&V: Add max time step of 0.01 to Delco Trainers Test_05

### PR DESCRIPTION
**Pull request by rpeacoc**
It fails at times with code changes when set to the default max time step of 1.0 s. With 0.01 s, results are the same as current release code (and earlier codes) with 1.0 s.

### CODE REVIEW

**Comment by rmcdermo** [comment]
@rpeacoc @preneke Rick, I already fixed the commit message once.  Now you have added it back.  Please fix it again.

**Comment by rpeacoc** [comment]
> @rpeacoc @preneke Rick, I already fixed the commit message once. Now you have added it back. Please fix it again.

Done.  FYI, it was not something I did intentionally. Github did it on its own as part of a remote update, merge, push, ... command line operation.

**Comment by rmcdermo** [comment]
No, you have not fixed it.  The commit and message are still there when I update my repo and look at the log.

**Comment by rpeacoc** [comment]
It shows as fixed at my end.  If I go to the code change at https://github.com/firemodels/cfast/pull/2079, it shows as changed by me 20 minutes ago.

**Comment by rmcdermo** [comment]
Go [here](https://github.com/firemodels/cfast/commits/master/) and look through the full commit log.

**Comment by rpeacoc** [comment]
Yup. That's how I got to #2079. I do see that in the main list it shows up wrong. If you click on that it shows me changing it. I sorry, but I don't see why it's not showing up on the main list.
________________________________

**Comment by rmcdermo** [comment]
The only way I see to fix this easily right now is for all of us to reset (not revert) to
```
53a4b87f3 CFAST: fixed error numbers (preneke)
```
1. Save the current state of your repo.
2. Do a reset locally to 53a4b87f3.
3. I will reset the master branch accordingly.
4. Then you do the usual update (all should be in sycn).
5. Then you add back your recent changes, commit, PR

**Comment by rmcdermo** [comment]
Are we all on board with this?  When you push to your GitHub fork after you reset you will need to use --force.  Then all the wonky commits will be gone.

**Comment by preneke** [comment]
I don't know how to do step 2. Is this a reset on my PC.

**Comment by rmcdermo** [comment]
> I don't know how to do step 2. Is this a reset on my PC.

Yes.  First, make a copy of whatever files you want to pop back to the repo.  Then do,

```
$ git reset 53a4b87
$ git push --force origin master
```

**Comment by preneke** [comment]
Done.

**Comment by rpeacoc** [comment]
I’m on board. I’ll do it at my end. ThanksRSent from my iPadOn Feb 15, 2024, at 2:48 PM, Randy McDermott ***@***.***> wrote:﻿
Are we all on board with this?  When you push to your GitHub fork after you reset you will need to use --force.  Then all the wonky commits will be gone.

**Comment by rmcdermo** [comment]
OK, the firemodels/master branch is good now.  You can add your changes and give it a new commit and things should be back to normal.

**Comment by rmcdermo** [comment]
OK, now someone needs to add back the file changes between reset and what you stored before the reset.

**Pull request merged**
