### PR TITLE
Adiabatic surface temperature for target

### PR DESCRIPTION
**Pull request by andytamhk168**
Additions to 1) cfast_data.f90, 2) cfast_structures.f90, 3) input_namelist.f90, and 4) target.f90.
-item 1 and 2: new parameters added
-item 3: new diag mode "AST" and input parameters for device namelist added
-item 4: new subroutine to carry out the AST calculation included

Cfastbot was ran on my end.

Verification case is created. Results obtained from the verification case agree well. The verification case and changes to different scripts will be included in the next pull request.

### CODE REVIEW

**Comment by mcgratta** [comment]
Rick, can you review this?

**Comment by andytamhk168** [comment]
Dear all,

Only one important change to the target subroutine is made. 

If the target is adiabatic, the target surface temperature will be calculated using the new subroutine. This would require the user to specify convective heat transfer coefficients to the target. The calculation is similar to that can be found in FDS. 

Otherwise, the surface temperature calculation will be carried out using the original logarithms. Therefore, the changes I made should not affect any V and V cases. 

In the future, Please kindly let me know if changes are needed. I can make appropriate changes (names of parameters, coding structure, and etc)  to the code for consistency.

Updates to verification guide and user guide will be submitted in the next pull request.

Thanks,
Andy

**Comment by mcgratta** [comment]
Is the default heat transfer coefficient the same as the one used for the walls?

**Comment by rpeacoc** [comment]
No. It’s totally a user input. That’s part of why I’d like Glenn to look at it. Seems we ought to be able to calculate it just like we do for regular targets and walls.

**Pull request merged**
