### PR TITLE
Verification cases for radiation and target routines and a word document including the results associated to the case

### PR DESCRIPTION
**Pull request by andytamhk168**
Please kindly review the updates.

Update(2017_11_17): 1) Fix 2 bugs in target.f90, 2) Add new namelist group for disgnosis, 3) Incorporate changes in cfast_data, input, input_namelist, radiation, and target.f90 to facilitate simulation of verification case on CFAST radiation and target models.

Descriptions of the verification case and the associated results are included in below document.
[Verification case.docx](https://github.com/firemodels/cfast/files/1483036/Verification.case.docx)

### CODE REVIEW

**Comment by mcgratta** [comment]
Andy, did you run cfastbot on your repository? This will make sure that you have not broken something.

**Comment by andytamhk168** [comment]
I am running it now and will inform you when it is done. Thank you.

**Comment by rpeacoc** [comment]
Send me the files cfast_validation_scatterplot_output.csv in the repo folder Utilities/Matlab once it finishes running and I can look at the differences to the latest accepted CFAST.

**Comment by rpeacoc** [comment]
cfastbot results for this match the ones for the currently accepted version.  I'll accept the pull request and so some slight code cleanup for style.

**Comment by andytamhk168** [comment]
Thank you very much. I will remove all those location reminders for the changes, such as "ANDY", in the code.

**Comment by rpeacoc** [comment]
I get a bunch of compile errors at least in radiation.f90.  Is there a file you forgot to commit?

ifort -c /Qsave /Qinit:zero /debug:full /Z7 /Od /extend_source:132 /warn:all /warn:nointerfaces /Qtrapuv /fp:strict /fp:except /traceback /check:all /stand:f08 -fpp -DGITHASH_PP=\"CFAST7.2.3-248-gb18a2f8\" -DGITDATE_PP=\""Fri Nov 17 14:36:12 2017 -0500\""  -DVERSION_PP=\""Test Version     :\"" -DBUILDDATE_PP=\""Fri 11/17/2017  02:39 PM\"" ../../../Source/CFAST/radiation.f90
Intel(R) Visual Fortran Intel(R) 64 Compiler for applications running on Intel(R) 64, Version 18.0.0.124 Build 20170811
Copyright (C) 1985-2017 Intel Corporation.  All rights reserved.

../../../Source/CFAST\radiation.f90(13): error #6580: Name in only-list does not exist or is not accessible.   [PARTIAL_PRESSURE_H2O]
    use fire_data, only: n_fires, fireinfo, partial_pressure_h2o, partial_pressure_co2, soot_volume_fraction, tempTgas
--------------------------------------------^
../../../Source/CFAST\radiation.f90(13): error #6580: Name in only-list does not exist or is not accessible.   [PARTIAL_PRESSURE_CO2]
    use fire_data, only: n_fires, fireinfo, partial_pressure_h2o, partial_pressure_co2, soot_volume_fraction, tempTgas
------------------------------------------------------------------^
../../../Source/CFAST\radiation.f90(13): error #6580: Name in only-list does not exist or is not accessible.   [SOOT_VOLUME_FRACTION]
    use fire_data, only: n_fires, fireinfo, partial_pressure_h2o, partial_pressure_co2, soot_volume_fraction, tempTgas
----------------------------------------------------------------------------------------^
../../../Source/CFAST\radiation.f90(13): error #6580: Name in only-list does not exist or is not accessible.   [TEMPTGAS]
    use fire_data, only: n_fires, fireinfo, partial_pressure_h2o, partial_pressure_co2, soot_volume_fraction, tempTgas
--------------------------------------------------------------------------------------------------------------^
../../../Source/CFAST\radiation.f90(66): error #6404: This name does not have a type, and must have an explicit type.   [DIAGFLAG]
        if (diagflag == .true.) then !(ANDY)
------------^
../../../Source/CFAST\radiation.f90(67): error #6404: This name does not have a type, and must have an explicit type.   [TEMPTGAS]
            roomptr%temp(u) = tempTgas + 273.15_eb
------------------------------^
../../../Source/CFAST\radiation.f90(934): error #6404: This name does not have a type, and must have an explicit type.   [PARTIAL_PRESSURE_CO2]
        plg = partial_pressure_co2*l
--------------^
../../../Source/CFAST\radiation.f90(950): error #6404: This name does not have a type, and must have an explicit type.   [PARTIAL_PRESSURE_H2O]
        plg = partial_pressure_h2o*l
--------------^
../../../Source/CFAST\radiation.f90(965): error #6404: This name does not have a type, and must have an explicit type.   [SOOT_VOLUME_FRACTION]
        vfs = soot_volume_fraction
--------------^
../../../Source/CFAST\radiation.f90(950): remark #7712: This variable has not been used.   [PARTIAL_PRESSURE_H2O]
        plg = partial_pressure_h2o*l
--------------^
../../../Source/CFAST\radiation.f90(934): remark #7712: This variable has not been used.   [PARTIAL_PRESSURE_CO2]
        plg = partial_pressure_co2*l
--------------^
../../../Source/CFAST\radiation.f90(965): remark #7712: This variable has not been used.   [SOOT_VOLUME_FRACTION]
        vfs = soot_volume_fraction
--------------^
../../../Source/CFAST\radiation.f90(67): remark #7712: This variable has not been used.   [TEMPTGAS]
            roomptr%temp(u) = tempTgas + 273.15_eb
------------------------------^
../../../Source/CFAST\radiation.f90(66): remark #7712: This variable has not been used.   [DIAGFLAG]
        if (diagflag == .true.) then !(ANDY)
------------^
compilation aborted for ../../../Source/CFAST/radiation.f90 (code 1)
make: *** [radiation.obj] Error 1

**Comment by rpeacoc** [comment]
I reverted the changes since the code does not compile.  Resubmit with a complete set of files and we'll try again.  I'd suggest doing it in two steps: 1) just the bug fix for targets.  2. Once it's been verified that the bug fix works, submit a second pull request with the diagnostic data update.

**Comment by andytamhk168** [comment]
I missed the updated cfast_data.f90 from the pull request.

**Pull request merged**
