### PR TITLE
Develop namelist input: 3 new files added. 2 existing files modified.

### PR DESCRIPTION
**Pull request by andytamhk168**
*** Circulating new updates for improvement. Do not commit yet ***

2 new features added:

1 ) Namelist input through use of new input file (.cfast)
2 ) Input file conversion: to convert format of .in file to that of .cfast file
Minor changes to existing files:

1 ) input.f90, and 2 ) utilities.f90
3 modules added:

1 ) new_input.f90, 2 ) conversion.f90, and 3 ) namelist_data.f90

Also, cleaned the updates.

### CODE REVIEW

**Comment by andytamhk168** [comment]
I closed the previous pull request as I included too many unnecessary items.

**Comment by andytamhk168** [comment]
I closed the previous request as I accidentally included too many unnecessary items.

**Comment by rpeacoc** [comment]
Can you circulate a sample namelist input file? We all need to agree on the format of the new input file before things get set in the release code.  We should all get together and discuss the changes next week.

**Comment by andytamhk168** [comment]
[name list input.docx](https://github.com/firemodels/cfast/files/1166770/name.list.input.docx)

Please find attached an input file consisted of all the keywords and features. Normally, I use the existing names/words that the current CFAST is using.

**Comment by andytamhk168** [comment]
The input for a "keyword" can be entered in a single line with features separated by comma or space. Each keyword input will end with a "/". Inputs can also be entered through multiple lines. 

I open the docx file I have just uploaded. It seems that the inputs are shifted. However, it will not affect how they will be read in the code.

**Comment by rmcdermo** [comment]
Please upload a plain .txt file.

**Comment by andytamhk168** [comment]
[namelist input.txt](https://github.com/firemodels/cfast/files/1166960/namelist.input.txt)

Please find the .txt file. Thanks.

**Comment by andytamhk168** [comment]
The final wording for the keywords and elements can be adjusted.

**Pull request closed without merging**
