### PR TITLE
Correct some typos

### PR DESCRIPTION
**Pull request by sbenkorichi**

### CODE REVIEW

**Comment by sbenkorichi** [comment]
I would like also to know, whether this guides are written in US or GB or they're mixed?

**Comment by mcgratta** [comment]
What do you mean?

**Comment by sbenkorichi** [comment]
I'm speaking about the spelling Kevin, is the main one US spelling or mixed with GB one? Because, I also saw some words are in GB spelling.

**Comment by mcgratta** [comment]
We typically use US spelling. Some words can be spelled a few different ways, even in US.

**Comment by sbenkorichi** [comment]
Ok !

**Pull request merged**
